-- Create crypto_data table
create table crypto_data (
    id bigint generated by default as identity primary key,
    data jsonb not null,
    count integer not null,
    last_updated timestamp with time zone default timezone('utc'::text, now()) not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create an index on last_updated for faster queries
create index idx_crypto_data_last_updated on crypto_data(last_updated desc);

-- Enable Row Level Security (RLS)
alter table crypto_data enable row level security;

-- Create policy to allow anyone to read
create policy "Allow public read access"
    on crypto_data for select
    to anon
    using (true);

-- Create policy to allow only service role to insert
create policy "Allow service role to insert"
    on crypto_data for insert
    to service_role
    using (true);
